"""empty message

Revision ID: ae2ba5c241ff
Revises: 029e9d57538a
Create Date: 2021-03-14 02:03:02.328931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2ba5c241ff'
down_revision = '029e9d57538a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'title')
    # ### end Alembic commands ###
